version: "3.1"

services:

  jenkins-master:
    image: ${HUB_USER:-sdelrio}/jenkins:${TAG:-latest}
    ports:
      - 50000:50000
      - 8080:8080
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
    volumes:
      - jm:/var/jenkins_home
      - jmshare:/usr/share/jenkins/ref
    deploy:
      resources:
        reservations:
          memory: 500M
        limits:
          memory: 1000M
    secrets:
      - jenkins-user
      - jenkins-pass

secrets:
  jenkins-user:
    external: true
  jenkins-pass:
    external: true

volumes:
  jm:
  jmshare:

